apiVersion: v1
kind: ConfigMap
metadata:
  name: docker
  namespace: weavek8sops
data:
  daemon.json: |
    {
      "dns": [ "8.8.8.8", "8.8.4.4" ],
      "log-driver": "json-file",
      "log-opts": {
        "max-size": "100m"
      },
      "exec-opts": [
        "native.cgroupdriver=cgroupfs"
      ]
    }
