apiVersion: v1
kind: ConfigMap
metadata:
  name: docker
  namespace: weavek8sops
data:
  daemon.json: |
    {
      "log-driver": "json-file",
      "log-opts": {
        "max-size": "100m"
      },
      "insecure-registries": [
        "172.25.0.2:5000",
        "registry.default.svc:5000",
        "netmoom.nerdland.local:4999"
      ],
      "exec-opts": [
        "native.cgroupdriver=cgroupfs"
      ]
    }
